version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/ssl/certs
      - ./src/html:/usr/share/nginx/html

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./src/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - 8000:80

  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./src/php:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
