version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./src/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - VIRTUAL_HOST=mysql.local.localhost
      - CERT_NAME=_woldcard.local.localhost
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin
    environment:
      - VIRTUAL_HOST=phpadmin.local.localhost
      - CERT_NAME=_woldcard.local.localhost
      - PMA_HOST=mysql
    restart: always

  php:
    container_name: php-apache
    build: ./php
    environment:
      - VIRTUAL_HOST=php.local.localhost
      - CERT_NAME=_woldcard.local.localhost
    volumes:
      - ./src/php:/var/www/html
    depends_on:
      - mysql
